### ISSUE TITLE
Wijziging testprocedure VISI-keurmerkcertificering

### ISSUE THREAD

**Issue by JanaxLooij** [bimloket/visi#52]
De VISI beheerorganisatie (CROW) kan VISI compliant softwareapplicaties een keurmerk toekennen. Om voor het VISI keurmerk in aanmerking te komen wordt het softwareproduct getest door een onafhankelijke instantie die het CROW rapporteert over de uitkomst van deze certificeringstest. Het testresultaat vormt de belangrijkste bron waarop het CROW zijn toekenningsbesluit baseert.

De testprocedure voor het verkrijgen van het VISI-keurmerk wordt op een aantal punten aangepast. Het betreft de volgende aanpassingen:

De leverancier van het VISI-compatibele softwareproduct is primair verantwoordelijk voor het testen op VISI-compatibiliteit. Voor de testprocedure laat de keurmerkaanvragende partij zien welke testen zijn uitgevoerd en welke resultaten deze testen te zien hebben gegeven.

Naast deze leverancierstesten organiseert de VISI beheerorganisatie een afsluitende cross-platform test waarbij de prestaties van de verschillende VISI-compatibele softwareproducten onderling getest worden.

Van beide keurmerktestonderdelen wordt een test/beoordelingsrapport opgesteld. Afhankelijk van een positief rapport wordt de VISI-beheerorganisatie geadviseerd het VISI-keurmerk toe te kennen.

VISI Keurmerkovereenkomst (PDF) (http://www.crow.nl/getmedia/de240c67-2455-423c-b57f-4a77afd01405/Procedure-VISI-keurmerk-v-1-02-dd-22-maart-2012.aspx)
VISI Keurmerkovereenkomst (PDF) (http://www.crow.nl/getmedia/239f9b3a-f1fd-45af-bdcb-b6231cc56e22/MODEL-VISI-Keurmerkovereenkomst-COMPLEET.aspx)

#### Attachments
[Notitie VISI Software Certificeringstest.docx](https://www.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=visi&WorkItemId=4612&FileAttachmentId=838)

#### This work item was migrated from CodePlex
CodePlex work item ID: '4612'
Assigned to: 'PeterWillems'
Vote count: '1'

**Comment by ArneBruinse** [comment]
[838.docx](https://github.com/bimloket/visi/files/6121792/838.docx)
codeplex document opgezocht en bijgevoegd
