### ISSUE TITLE
Open Standaard Digikoppeling gebruiken voor communicatie tussen SOAP servers

### ISSUE THREAD

**Issue by JanaxLooij** [bimloket/visi#53]
Achtergrond
Zie https://visi.codeplex.com/workitem/4602 voor het onderzoek naar DigiKoppeling
Zie https://visi.codeplex.com/workitem/1010 voor Waarborgen integriteit en authenticiteit van VISI-berichten

Technische oplossing
...

Backwards compatibility
...

Acties:

afstemmen met Logius over DigiKoppeling (actie: Roy=gedaan);
doorlezen van documentatie Digikoppeling (2.0/3.0?) (actie: PW);
zoeken naar methodes voor het verzenden van informatiepakketjes (actie: PW);
samenvatten van methodes met de relatie naar SOAP uit VISI Standaard (actie: PW);
...
beschrijven van de inpassing van Digikoppeling in VISI Standaard (m.a.w. SOAP richtlijn herzien);
doornemen van Logius documenten: Koppelvlakstandaard WUS, Koppelvlakstandaard Grote Berichten, Protocolbindingen voor StUF.
concept versie maken van Protocolbindingen voor VISI (actie: Ge);
concept implementatie maken van Protocolbindingen voor VISI (actie: Ge, JvG);
definitieve versie maken van Protocolbindingen voor VISI (actie: Paul Jansen).

#### Attachments
[e-mail Peter Willems vr 8-4-2016 1307.pdf](https://www.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=visi&WorkItemId=4613&FileAttachmentId=2924)
[Digikoppeling.docx](https://www.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=visi&WorkItemId=4613&FileAttachmentId=2925)
[Digikoppeling_3.0_Architectuur_v1.2.pdf](https://www.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=visi&WorkItemId=4613&FileAttachmentId=2926)
[stuf.bindingen.030203.pdf](https://www.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=visi&WorkItemId=4613&FileAttachmentId=3985)
[20160715 v1 Presentatie Digikoppeling Crow.pdf](https://www.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=visi&WorkItemId=4613&FileAttachmentId=3986)
[stuf.bindingen.030200.doc](https://www.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=visi&WorkItemId=4613&FileAttachmentId=3999)
[stuf.bindingen.030200.odt](https://www.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=visi&WorkItemId=4613&FileAttachmentId=4000)
[Stuf0301_20160603_pre-patch25.zip](https://www.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=visi&WorkItemId=4613&FileAttachmentId=4001)

#### This work item was migrated from CodePlex
CodePlex work item ID: '4613'
Assigned to: 'gspees'
Vote count: '1'

**Comment by JanaxLooij** [comment]
[jvgeijlswijk@8-4-2016]
Prioriteit is ingesteld.

**Comment by JanaxLooij** [comment]
[UnknownUser@8-4-2016]

**Comment by JanaxLooij** [comment]
[jvgeijlswijk@8-4-2016]
Actielijst is ingevuld.

**Comment by JanaxLooij** [comment]
[UnknownUser@8-4-2016]

**Comment by JanaxLooij** [comment]
[jvgeijlswijk@8-4-2016]
E-mail van Peter Willems met eerste resultaat van zoekactie is bijgevoegd.

**Comment by JanaxLooij** [comment]
[UnknownUser@8-4-2016]

**Comment by JanaxLooij** [comment]
[jvgeijlswijk@8-4-2016]
Ook de bijlagen van de e-mail van Peter Willems zijn bijgevoegd.

**Comment by JanaxLooij** [comment]
[UnknownUser@8-4-2016]

**Comment by JanaxLooij** [comment]
[jvgeijlswijk@8-4-2016]
Ook de bijlagen van de e-mail van Peter Willems zijn bijgevoegd.

**Comment by JanaxLooij** [comment]
[UnknownUser@8-4-2016]

**Comment by JanaxLooij** [comment]
[jvgeijlswijk@8-4-2016]
Ook de bijlagen van de e-mail van Peter Willems zijn bijgevoegd.

**Comment by JanaxLooij** [comment]
[jvgeijlswijk@8-4-2016]
Gé heeft een e-mail stuurt naar forumstandaardisatie@logius.nl met het verzoek voor een gesprek met iemand die technisch deskundig is in de materie van Digikoppeling.

**Comment by JanaxLooij** [comment]
[UnknownUser@8-4-2016]

**Comment by JanaxLooij** [comment]
[UnknownUser@9-9-2016]

**Comment by JanaxLooij** [comment]
[gspees@9-9-2016]
Document stuff bindingen toegevoegd

**Comment by JanaxLooij** [comment]
[UnknownUser@9-9-2016]

**Comment by JanaxLooij** [comment]
[gspees@9-9-2016]
Presentatie digikoppeling toegevoegd

**Comment by JanaxLooij** [comment]
[UnknownUser@9-9-2016]

**Comment by JanaxLooij** [comment]
[gspees@9-9-2016]
Ik was begonnen met document nabouwen voor VISI maar merk dat conversie van PDF naar Word niet goed gaat en dat dit veel tijd kost. Heb nu het originele document opgevraagd bij KING.

Geachte heer Groeneveld,

We hebben elkaar een keer ontmoet bij ons op kantoor in Amsterdam en via Hans Mulder en Sander Mooij ben ik ook naar je doorverwezen om een keer iets meer te vertellen over de open standaard VISI. Dat wil ik zeker graag een keer doen.

De concrete vraag die ik nu heb is of wij van het VISI Technisch Comité gebruik mogen maken van het document Protocolbindingen voor StUF Versie: 03.02. Wij willen graag onze eigen soap standaard vervangen voor die van DigiKoppeling. Omdat VISI voor een deel op STUF lijkt (beiden berichtenverkeer) kwamen we dit document tegen. Wij zouden dit document graag als basis gebruiken/deels overnemen om de Protocolbindingen voor VISI te beschrijven. Indien mogelijk zouden we graag het originele *.odt document ontvangen. Indien mogelijk zouden we ook graag contact willen opnemen met de auteurs van dit document.


Met vriendelijke groet,
Bakker & Spees 

Gé Spees (namens VISI Technisch Comité)

**Comment by JanaxLooij** [comment]
[gspees@13-1-2017]
reactie van de heer Groenveld
-------------
Beste Gé,

Dank voor je mail. Het is accoord wanneer je tekst hergebruikt ovv van de bron. Binnen KING is Henri Korver (henri.korver@kinggemeenten.nl) degene waar je inhoudelijk vragen aan kan stellen. 


Met vriendelijke groet,

Kees Groeneveld
Leveranciersmanagement / Marktontwikkelingen
Kwaliteitsinstituut Nederlandse Gemeenten (KING)

**Comment by JanaxLooij** [comment]
[gspees@13-1-2017]
mail naar de heer Korver
------
Geachte heer Korver,

Zou u mij het Word bestand van ‘Protocolbindingen voor StUF Versie: 03.02’ kunnen mailen zodat wij dit als bron kunnen gebruiken om Protocolbindingen voor de open standaard VISI te schrijven?


Met vriendelijke groet,
Technische Comité VISI

Gé Spees

**Comment by JanaxLooij** [comment]
[UnknownUser@13-1-2017]

**Comment by JanaxLooij** [comment]
[gspees@13-1-2017]
Beste Gé,

Bijgaand het bestand zowel in Open Office als in Word formaat. Het origineel is in Open Office gemaakt en vanuit daar heb ik het naar Word geconverteerd. In de conversie kan wel eens iets mis gaan, dus vandaar dat ik het origineel ook meestuur.

Mvg,
Henri

**Comment by JanaxLooij** [comment]
[UnknownUser@13-1-2017]

**Comment by JanaxLooij** [comment]
[gspees@13-1-2017]
het odt bestand

**Comment by JanaxLooij** [comment]
[UnknownUser@13-1-2017]

**Comment by JanaxLooij** [comment]
[gspees@13-1-2017]
zip bestand met xsd's en pdf's van stuff

**Comment by ArneBruinse** [comment]
Closed, want digikoppeling is alleen bedoeld voor communicatie tussen overheden.

**Comment by jvgeijlswijk** [comment]
Zie https://github.com/bimloket/visi/issues/96 voor oplossing voor "Europe-wide eSignature interoperability"
