### ISSUE TITLE
Raamwerk met niet-ascii tekens in keuzelijsten en omschrijvingen (enumerations & descriptions)

### ISSUE THREAD

**Issue by jvgeijlswijk** [bimloket/visi#68]
1.
Omschrijving van de vraag/opmerking zelf (bij voorkeur in het format van ‘userstory’):
"Als gebruiker wil ik de exacte straatnamen (inclusief vreemde tekens) terug zien in een selectielijst in een VISI-bericht, zodat ik de straatnamen direct kan herkennen" 

2.
Naam: Herman Algra / Kai Giese
Functie: Contractmanager
Organisatie: Ingenieursbureau Amsterdam

3.
Datum: 24-04-2019 17:02
Oorsprong van het verzoek: project Programma Constructieve Veiligheid Bruggen

4.
Waarop heeft de vraag betrekking: a. Open Standaard (VISI) & b. VISI-raamwerk

5.
Urgentie: "S" (should have; hinder kan worden omzeild in dagelijks werk; moet binnen redelijke termijn worden opgelost)

6.
Toelichting op de urgentie: 
nader te bepalen

## Open Standaard (VISI) / VISI Raamwerk
1.
Een "verbetervoorstel"

3. Verbetervoorstel
a.	Meer details aangaande de user story 
Jos Hamilton schreef op 24-04-2019 17:02:
_Uit de concept documentatie 1.6 die ik van Elisabeth heb mogen ontvangen staat bij header: <?xml version=”1.0” encoding=”UFT-8”…………………… Dit houdt in dat alleen een XML de ascii karakter decimaal 0 t/m 127 mag bevatten. Dus geen speciale tekens met bijvoorbeeld een dubbele punt. Ook houdt de XML spelregels in dat “, &, > , < en ‘ niet zomaar gebruikt mogen worden (gereserveerde karakters) maar vertaald moeten worden met &xxx;. Bij & dus &amp;

Ik heb mijn omzetter die de projectspecifieke raamwerken maakt zo aangepast dat die aan bovengenoemde uitgangspunten voldoet. Dit voor een grote groep tekens. Waarbij tekens met een trema e.d. heb omgezet naar de versie zonder deze toevoeging. Dit om te voorkomen dat dit alsnog handmatig te moeten doen. Het resultaat is TEKA. Ook heb ik een versie TELB gemaakt waar alleen de &xxx; is aangebracht en alle andere tekens niet zijn geconverteerd.

Ik zag toevallig dat raamwerken van B&S de string UFT-8 bevat. Het klopt dan dat de XML geaccepteerd wordt, maar dit is dan niet volgens de standaard. En kan ook niet als er met verschillende leveranciers gewerkt wordt.

Graag de XML TEKA testen en beproeven of &xxx; werkt. En eventueel TELB om te kijken hoe de eigen software überhaupt omgaat met vreemde tekens. Welke vreemde tekens er gebruikt zijn kunnen jullie nagaan op de tabbladen van het spreadsheet. Gelet de bovenstaande conclusie heb ik niet meer uitgeprobeerd hoe de descriptions hierop reageerden._

b.	Randvoorwaarden 
(“anything the solution can assume to be true when the use case begins”)

c.	Definiton of Done
(“anything that must be true when the use case is complete”)
•	Relevante functionele documentatie is aangepast.
•	Relevante technische documentatie is geactualiseerd.
•	Testscenario is toegevoegd.
•	Testraamwerk is geactualiseerd.
•	Keurmerktest is geactualiseerd.
•	De ‘reporter’ heeft het werk geaccepteerd.
•	Er is feedback van eindgebruiker(s)/vraagsteller gevraagd/gekregen op het opgeleverde product.

d.	Beschrijf het verbetervoorstel / of gewenst gedrag 
(“the set of steps the actors take to accomplish the goal of the use case. A clear description of what the system should do in response to each user action.”)

e.	Beschrijf de voordelen van de verbetering

f.	Beschrijf eventuele “Alternate Flows” 
(“capture the less common user/system interactions, such as being on a new computer and answering a security question)
Work around is om de "vreemde tekens" te vervangen door standaard tekens. Bijvoorbeeld: "ideeën" vervangen door "ideeen". Of  "<" vervangen door "kleiner dan".

g.	Beschrijf eventuele “Exception Flows”  
(“things that can happen that prevent the user from achieving their goal, such as providing an incorrect username and password).

[VISI MACRO versie 3.4 04-04-2019 - TEK.xlsx](https://github.com/bimloket/visi/files/3166027/VISI.MACRO.versie.3.4.04-04-2019.-.TEK.xlsx)

[IB_UAVgc_11L_TEKA_20XX-XXXX_24-04-2019_AMP-JH.zip](https://github.com/bimloket/visi/files/3166029/IB_UAVgc_11L_TEKA_20XX-XXXX_24-04-2019_AMP-JH.zip)

[Mail_Peter_Bonsma_20160925.pdf](https://github.com/bimloket/visi/files/3166034/Mail_Peter_Bonsma_20160925.pdf)

**Comment by jvgeijlswijk** [comment]
https://www.utf8-chartable.de/unicode-utf8-table.pl?utf8=0x

**Comment by JanaxLooij** [comment]
```
De gereserveerde XML tekens moeten goed vertaald worden met het ampersand teken (&) en moeten bij onderstaande gevallen (bij een enumeration waarde in de XSD restrictie van een UDT) dubbel worden escaped met &amp; voor een geldig raamwerk. Buiten enumeration is een enkele escape voldoende.

ASCII karakter | XML vertaling
“ | &amp;quot;
& | &amp;amp;
> | &amp;gt;
< | &amp;lt;
‘ | &amp;apos;
```

**Comment by jvgeijlswijk** [comment]
Het testraamwerk is uitgebreid met 1) &amp; (&) en &gt; (>) in description en 2) &amp;quot; (") en &amp;amp; (&) en &amp;gt; (>) en &amp;lt; (<) en &amp;apos; (') in enumeration, en 3) diverse symbolen (¥çëäïöü®) in description en enumeration.

**Comment by gspees** [comment]
Item toegevoegd aan:
[https://github.com/bimloket/visi/wiki/2.-De-belangrijkste-wijzigingen-in-de-VISI-systematiek](2.-De-belangrijkste-wijzigingen-in-de-VISI-systematiek)
en dit item gesloten
