### ISSUE TITLE
Implentatie: Toegang tot juiste kennis

### ISSUE THREAD

**Issue by edelater** [bimloket/visi#79]
> Dit issue is onderdeel van een serie issues waar Future Insight tegenaan liep tijdens implementatie van VISI.

### toegang tot de juiste kennis;
  - in eerste instantie contact met CROW en toegang tot codeplex
  - antwoorden via codeplex leveren alleen meer vragen, lastig om snel voorwaarts te gaan
  - CROW heeft geen technische kennis; verwijst door naar TNO
  - TNO heeft te weinig technische kennis
  - VISI-Consultant gesproken; te weinig technische kennis
  - via BIM-Loket/CROW in de VISI werksessie 'gemanoeuvreerd' en daar uiteindelijk toegang gekregen tot een programmeur met de juiste kennis.
  - veel gegevens in de toen beschikbare handleiding bleek achterhaald, onjuist en/of onvolledig

**Comment by niekpluijmert** [comment]
technische documentatie

**Comment by ElisabethKloren** [comment]
Deze issue wordt in 2020 aangepakt met een update van de technische documentatie. Ook wordt een externe partij ingeschakeld hiervoor, in de hoop dat er een onafhankelijke partij is die bij implementaties kan helpen in de toekomst (niet zijnde een concurrent). Ik sluit hierbij deze issue af.
