### ISSUE TITLE
Implementatie: Dossier / Archief

### ISSUE THREAD

**Issue by edelater** [bimloket/visi#82]
> Dit issue is onderdeel van een serie issues waar Future Insight tegenaan liep tijdens implementatie van VISI.

### Dossier / Archief
  - voor windows:
    - te lange paden: https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#maximum-path-length-limitation
    - directory namen van projectdata klopt niet: 2010-12-31T00:00:00.0Z is geen geldige directory naam
  - workaround: linux

**Comment by ArneBruinse** [comment]
ons voorstel is om deze fouten in de 1.7 systematiek te corrigeren. besproken in de expertcommisie van 14022020.
Aanwezig Niek, Jos, Michon, Jens, Jeroen en Arne
