### ISSUE TITLE
Implementatie: Promotor

### ISSUE THREAD

**Issue by edelater** [bimloket/visi#84]
> Dit issue is onderdeel van een serie issues waar Future Insight tegenaan liep tijdens implementatie van VISI.

### Promotor
  - namespace uit projectType in _7.xml wordt niet overgenomen in 10.xsd
  - minOccurs / maxOccurs (voor rijen van tabellen) wordt niet overgenomen in xsd.
  - instelling voor het verplichten van appendices wordt niet overgenomen in xsd;
  - C++ source code van Promotor is vrijwel niet aan te passen zonder heel specifieke kennis (ondanks source code).

**Comment by ArneBruinse** [comment]
dit wordt opgelost in #87

**Comment by jvgeijlswijk** [comment]
T.a.v. het laatste punt "C++ source code van Promotor is vrijwel niet aan te passen zonder heel specifieke kennis (ondanks source code)" bevat de documentatie van VISI Standaard versie 1.4 een document van de hand van Peter Bonsma:
[https://github.com/bimloket/visi/blob/master/1_technische_documentatie/archief/VISI%201.4%20documentatie/VISI%20syst.1.4%20Bijlage%209%20Toelichting%20op%20werking%20Promotor%20CC-BY-NC-SA.pdf](Toelichting op de werking van de Promotor)

Dit document heeft de kwalificatie "INFORMATIEF", en geeft een beschrijving op hoofdlijnen van de technische opbouw van de VISI Standaard (_2.exp, _3.xsd, _5.exp, _7.xml, etc.) en welke function calls uit de dll van de Promotor gebruikt kunnen worden voor een bepaalde conversie. Bijvoorbeeld conversie van _2.exp naar _3.xsd.

Het document beschrijft niet de functionele logica, die toegepast wordt bij een conversie. Op pagina 5 wordt slechts één voorbeeld van dergelijke logica gegeven:
"_For example, the ID attribute value of a *Type data element is interpreted as the name of its XSD complex element counterpart. As a result, the ID attribute in an interaction framework shouldn't be something like ID=”Role003” but more like ID=”Project_Manager”._" 

Een andere voorbeeld van dergelijke logica is:
Eerste letter van het ID van een SimpleElementType uit raamwerk (_7.xml) wordt geconverteerd naar een kleine letter in het gepromote raamwerk (10.xsd). Dus <SimpleElementType ID="REACTIETERMIJN"> (uit het raamwerk) wordt <rEACTIETERMIJN>2022-02-22</rEACTIETERMIJN>

N.B. Ook voor de eerste letter van het ID van een ComplexElementType uit het raamwerk past de Promotor een dergelijke logica toe. Echter dan een conversie naar een hoofdletter.
