### ISSUE TITLE
Implementatie: Certificering

### ISSUE THREAD

**Issue by edelater** [bimloket/visi#85]
> Dit issue is onderdeel van een serie issues waar Future Insight tegenaan liep tijdens implementatie van VISI.

### certificering
  - rommelig
    - geen duidelijk plan van aanpak (ondanks test-raamwerk)
    - test-raamwerk/psb niet volledig (rol wisselingen)
    - met name de 'soft requirements' zijn niet te toetsen ('probeer ongeauthoriseerd toegang te krijgen').
  - onduidelijkheden inzake de 'cross platform test'
  - wc-eend adviseert wc-eend: geen __onafhankelijke__ certificering mogelijk. certificering is vooralsnog afhankelijk van huidige leveranciers/concurrenten.

**Comment by niekpluijmert** [comment]
Het punt van de certificering wordt meegenomen door het BIM-loket in de herijking van VISI.

**Comment by ArneBruinse** [comment]
@edelater zou je een nieuwe us aan willen maken met daarin de gebreken in het test-raamwerk/psb, zodat we die op kunnen pakken?
